# Pandas
- Good for handling dataset with different data types

In [2]:
import pandas as pd

## DataFrame

### Create

#### Dictionary

In [10]:
dict = { 
    "country": ["Brazil", "Russia", "India", "China", "South Africa"],
    "capital": ["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"],
    "area": [8.516, 17.10, 3.286, 9.597, 1.221],
    "population": [200.4, 143.5, 1252, 1357, 52.98]
}
brics = pd.DataFrame(dict)
brics.head()

        country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98

In [11]:
brics.index = ["BR", "RU", "IN", "CH", "SA"]
brics.head()

         country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

#### Import

In [13]:
brics = pd.read_csv('datasets/brics.csv', index_col=0)
brics.head()

                 country    capital    area  population
country_ab
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98